name: rag_qa_env1
dependencies:
  - python=3.12.2
  - langchain==0.1.12
  - langchain-openai==0.0.8
  - langchain-community==0.0.29
  - streamlit==1.32.2
  - chromadb==0.4.24
  - pyngrok==7.1.5
  - pip:
    - git+
  - pandas
  - numpy
